### ISSUE TITLE
fix: pr_evaluation wokrflow has conflict

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cookiecutter-python#18]
The `pr_evaluation` workflow doesn't work.

Error:

```text
The workflow is not valid. .github/workflows/pr_validation.yaml (Line: 13, Col: 12): Job 'detect-unresolved-conflicts' depends on unknown job 'semantic_pr'.
```

Change the dependency of the workflow, can be fixed by moving them in topological order. Also set specific event for each workflow, current they all run whenever the PR is edited, repopend etc etc, but semantic PR  check should only be run again if the PR title is edited, similarly map other checks to their conditions as well, this will allow us to stop not run workflow uselessly.

**Comment by uniqueg** [comment]
Thanks for reporting. But if you prepare a fix, please only focus on the fix - don't include the other stuff you mention on workflow triggering, that's a separate issue (possibly more).
